/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unicam.cs.mpgc.rpg129078;
import java.util.Scanner;

import java.util.Scanner;

public class App {

    public static void turnoCombattimento(Giocatore giocatore, Nemico nemico, Scanner scanner) {

        System.out.println("\n=== TURNO DI COMBATTIMENTO ===");

        System.out.println("Scegli azione:");
        System.out.println("1 - Attacca");
        System.out.println("2 - Abilità");

        int scelta = scanner.nextInt();

        if (scelta == 1) {

            System.out.println(">> Attacco");

            giocatore.attacca(nemico);

            System.out.println("Vita nemico: " + nemico.getVitaCorrente());
        }

        if (scelta == 2) {

            System.out.println(">> Abilità");

            Abilita abilita = giocatore.getAbilita();

            if (giocatore.getEnergiaCorrente() >= abilita.costoEnergia()) {

                giocatore.setEnergiaCorrente(
                        giocatore.getEnergiaCorrente() - abilita.costoEnergia()
                );

                abilita.usa(giocatore, nemico);

                System.out.println("Usata abilità: " + abilita.nome());
                System.out.println("Effetto: " + abilita.effetto());

            } else {
                System.out.println("Energia insufficiente!");
            }

            System.out.println("Vita nemico: " + nemico.getVitaCorrente());
        }

        // 🔁 RISPOSTA NEMICO
        System.out.println("\n>> Nemico risponde");

        nemico.attacca(giocatore);

        System.out.println("Vita giocatore: " + giocatore.getVitaCorrente());
    }

    public static void main(String[] args) {

        Scanner scanner = new Scanner(System.in);

        Giocatore giocatore = new Giocatore(
                "Impiegato",
                100,
                50,
                new Penna(),
                new PremioProduzione()
        );

        Nemico nemico = new Nemico(
                "Capo Ufficio",
                80,
                15,
                TipoNemico.NORMALE
        );

        System.out.println("=== INIZIO COMBATTIMENTO ===");

        while (giocatore.getVitaCorrente() > 0 && nemico.getVitaCorrente() > 0) {

            turnoCombattimento(giocatore, nemico, scanner);

            System.out.println("\n--- STATO ---");
            System.out.println("Giocatore HP: " + giocatore.getVitaCorrente());
            System.out.println("Nemico HP: " + nemico.getVitaCorrente());
        }

        System.out.println("\n=== FINE COMBATTIMENTO ===");

        if (giocatore.getVitaCorrente() > 0) {
            System.out.println("Hai vinto!");
        } else {
            System.out.println("Hai perso!");
        }

        scanner.close();
    }
}
