/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unicam.cs.mpgc.rpg129078;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

/**
 * Entry point dell'applicazione JavaFX.
 * Carica la schermata del menu principale.
 */
public class App extends Application {

    @Override
    public void start(Stage stage) throws Exception {
        Parent root = FXMLLoader.load(
                getClass().getResource("/it/unicam/cs/mpgc/rpg129078/menu.fxml")
        );
        Scene scene = new Scene(root);
        stage.setTitle("SOPRAVVIVI ALL'UFFICIO");
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}

